language: cpp
dist: focal

sudo: false

matrix:
  include:
    - compiler: gcc
      env: BUILD_TYPE=Coverage
    - compiler: gcc
      env: BUILD_TYPE=Debug
    - compiler: gcc
      env: BUILD_TYPE=Release
    - compiler: clang
      env: BUILD_TYPE=Debug

addons:
  apt:
    update: true
    packages:
      - liblz4-dev
  homebrew:
    update: true
    packages:
    - lz4

os:
  - linux
  - osx

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make

script:
  - ctest -V

after_success:
  - if [ "${BUILD_TYPE}" == "Coverage" ]; then bash <(curl -s https://codecov.io/bash); fi

